[Metadata]
Name=ThinkPad
Name[zh_CN]=ThinkPad
Version=1
Author=kscii-linux
Description=Black and ThinkPad red theme for kscii-linux
ScaleWithDPI=True

[InputPanel]
NormalColor=#e0e0e0
HighlightCandidateColor=#ffffff
HighlightColor=#ffffff
HighlightBackgroundColor=#E2000F
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=6
Right=6
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Background]
Color=#000000
BorderColor=#E2000F
BorderWidth=2

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#E2000F

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#e0e0e0
HighlightCandidateColor=#ffffff

[Menu/Background]
Color=#000000
BorderColor=#E2000F
BorderWidth=2

[Menu/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/Highlight]
Color=#E2000F

[Menu/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu/Separator]
Color=#333333

[Menu/TextMargin]
Left=6
Right=6
Top=5
Bottom=5

[AccentColorField]
0=Input Panel Border
1=Input Panel Highlight Candidate Background
2=Input Panel Highlight
3=Menu Border
4=Menu Separator
5=Menu Selected Item Background
