# Fcitx5 全局配置
# ThinkPad Engineering Edition

[Hotkey]
# Super+Space 切换输入法（与 niri 的 Mod+Space 对应；
# niri 默认不拦截 Super+Space，因此此快捷键可正常生效）
TriggerKeys=Super+space
EnumerateForwardKeys=
EnumerateBackwardKeys=

[Behavior]
ActiveByDefault=False
ShareInputState=Program
PreeditEnabledByDefault=True
ShowUnkownInputMethodInfo=True
CompactInputMethodGroupInfo=False
DefaultPageSize=6
